esphome:
  name: d1mini2
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "example_ssid"
  password: "example_pass"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Mini2 Fallback Hotspot"
    password: "example_fallback_pass"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

sensor:
  - platform: dht
    pin: 14
    temperature:
      name: "D1Mini2 Temperature"
    humidity:
      name: "D1Mini2 Humidity"
    model: DHT22
    update_interval: 5s

switch:
  - platform: gpio
    name: "D1Mini2 Built-in led"
    pin:
      number: 2
      inverted: yes

