esphome:
  name: d1mini4
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "example_ssid"
  password: "example_pass"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Mini4 Fallback Hotspot"
    password: "example_fallback_pass"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

uart:
  rx_pin: D1
  tx_pin: D2
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: "my_mhz19_id"
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 20s
    automatic_baseline_calibration: false
  - platform: dht
    pin: 14
    temperature:
      name: "D1Mini4 Temperature"
    humidity:
      name: "D1Mini4 Humidity"
    model: DHT22
    update_interval: 5s

switch:
  - platform: gpio
    name: "D1Mini4 Built-in led"
    pin:
      number: 2
      inverted: yes
  - platform: template
    name: "MH-Z19 ABC"
    optimistic: true
    on_turn_on:
      mhz19.abc_enable: my_mhz19_id
    on_turn_off:
      mhz19.abc_disable: my_mhz19_id

