- id: '1630072245373'
  alias: Home Assistant check state
  description: Home Assistant ping
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: -> pong
  mode: single
- id: '1630072712035'
  alias: send_sensors
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: "4 Temp - {{ states.sensor.d1mini4_temperature.state}} \n4 Humidity\
        \ - {{ states.sensor.d1mini4_humidity.state }}\n4 CO2 - {{ states.sensor.d1mini4_mh_z19_co2_value.state\
        \ }}\n3 Temp - {{ states.sensor.d1mini3_temperature.state}} \n3 Humidity -\
        \ {{ states.sensor.d1mini3_humidity.state }}"
      disable_notification: true
  mode: single
- id: '1630073835092'
  alias: sensors
  description: Send Sensors
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /sensors
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: "Sensors - \n5 Temp - {{ states.sensor.d1mini5_temperature.state}}\
        \ \n5 Humidity - {{ states.sensor.d1mini5_humidity.state }}\n5 CO2 - {{ states.sensor.d1mini5_mh_z19_co2_value.state\
        \ }}\n4 Temp - {{ states.sensor.d1mini4_temperature.state}} \n4 Humidity -\
        \ {{ states.sensor.d1mini4_humidity.state }}\n4 CO2 - {{ states.sensor.d1mini4_mh_z19_co2_value.state\
        \ }}  \n3 Temp - {{ states.sensor.d1mini3_temperature.state}} \n3 Humidity\
        \ - {{ states.sensor.d1mini3_humidity.state }}"
  mode: single
- id: '1630155873570'
  alias: Notify about HA shutdown
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.telegram_notifier
    data:
      message: Home Assistant - shutdown
  mode: single
- id: '1630155941106'
  alias: Notify about HA start
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.telegram_notifier
    data:
      message: Home Assistant - start
  mode: single
