esphome:
  name: d1mini6
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Mini6 Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: d1mini6_mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: d1mini6_mhz19_id

ota:

web_server:
  port: 80

uart:
  rx_pin: D1
  tx_pin: D2
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: "d1mini6_mhz19_id"
    co2:
      name: "D1Mini6 MH-Z19 CO2 Value"
    temperature:
      name: "D1Mini6 MH-Z19 Temperature"
    update_interval: 20s
    automatic_baseline_calibration: false
#  - platform: dht
#    pin: 14
#    temperature:
#      name: "D1Mini6 Temperature"
#    humidity:
#      name: "D1Mini6 Humidity"
#    model: DHT22
#    update_interval: 5s

switch:
  - platform: gpio
    name: "D1Mini6 Built-in led"
    pin:
      number: 2
      inverted: yes
  - platform: template
    name: "D1Mini6 MH-Z19 ABC"
    optimistic: true
    on_turn_on:
      mhz19.abc_enable: d1mini6_mhz19_id
    on_turn_off:
      mhz19.abc_disable: d1mini6_mhz19_id

