esphome:
  name: d1mini1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Mini1 Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

sensor:
  - platform: dht
    pin: 14
    temperature:
      name: "D1Mini1 Temperature"
    humidity:
      name: "D1Mini1 Humidity"
    model: DHT22
    update_interval: 5s

switch:
  - platform: gpio
    name: "D1Mini1 Built-in led"
    pin:
      number: 2
      inverted: yes
  - platform: gpio
    name: "D1Mini1 Led"
    pin:
      number: 12

